a = {
    'MODEL_NAME':
    'R50_AOTL',
    'MODEL_VOS':
    'aot',
    'MODEL_ENGINE':
    'aotengine',
    'MODEL_ALIGN_CORNERS':
    True,
    'MODEL_ENCODER':
    'resnet50',
    'MODEL_ENCODER_PRETRAIN':
    './pretrain_models/resnet50-0676ba61.pth',
    'MODEL_ENCODER_DIM': [256, 512, 1024, 1024],
    'MODEL_ENCODER_EMBEDDING_DIM':
    256,
    'MODEL_DECODER_INTERMEDIATE_LSTT':
    True,
    'MODEL_FREEZE_BN':
    True,
    'MODEL_FREEZE_BACKBONE':
    False,
    'MODEL_MAX_OBJ_NUM':
    10,
    'MODEL_SELF_HEADS':
    8,
    'MODEL_ATT_HEADS':
    8,
    'MODEL_LSTT_NUM':
    3,
    'MODEL_EPSILON':
    1e-05,
    'MODEL_USE_PREV_PROB':
    False,
    'TRAIN_LONG_TERM_MEM_GAP':
    2,
    'TRAIN_AUG_TYPE':
    'v1',
    'TEST_LONG_TERM_MEM_GAP':
    5,
    'TEST_SHORT_TERM_MEM_SKIP':
    1,
    'EXP_NAME':
    'default_R50_AOTL',
    'STAGE_NAME':
    'PRE_YTB_DAV',
    'DATASETS': ['youtubevos', 'davis2017'],
    'DATA_WORKERS':
    8,
    'DATA_RANDOMCROP': (465, 465),
    'DATA_RANDOMFLIP':
    0.5,
    'DATA_MAX_CROP_STEPS':
    10,
    'DATA_SHORT_EDGE_LEN':
    480,
    'DATA_MIN_SCALE_FACTOR':
    0.7,
    'DATA_MAX_SCALE_FACTOR':
    1.3,
    'DATA_RANDOM_REVERSE_SEQ':
    True,
    'DATA_SEQ_LEN':
    5,
    'DATA_DAVIS_REPEAT':
    5,
    'DATA_RANDOM_GAP_DAVIS':
    12,
    'DATA_RANDOM_GAP_YTB':
    3,
    'DATA_DYNAMIC_MERGE_PROB':
    0.3,
    'PRETRAIN':
    True,
    'PRETRAIN_FULL':
    True,
    'PRETRAIN_MODEL':
    './result/default_R50_AOTL/PRE/ema_ckpt/save_step_100000.pth',
    'TRAIN_TOTAL_STEPS':
    100000,
    'TRAIN_START_STEP':
    0,
    'TRAIN_WEIGHT_DECAY':
    0.07,
    'TRAIN_WEIGHT_DECAY_EXCLUSIVE': {},
    'TRAIN_WEIGHT_DECAY_EXEMPTION': [
        'absolute_pos_embed', 'relative_position_bias_table', 'relative_emb_v',
        'conv_out'
    ],
    'TRAIN_LR':
    0.0002,
    'TRAIN_LR_MIN':
    1e-05,
    'TRAIN_LR_POWER':
    0.9,
    'TRAIN_LR_ENCODER_RATIO':
    0.1,
    'TRAIN_LR_WARM_UP_RATIO':
    0.05,
    'TRAIN_LR_COSINE_DECAY':
    False,
    'TRAIN_LR_RESTART':
    1,
    'TRAIN_LR_UPDATE_STEP':
    1,
    'TRAIN_AUX_LOSS_WEIGHT':
    1.0,
    'TRAIN_AUX_LOSS_RATIO':
    1.0,
    'TRAIN_OPT':
    'adamw',
    'TRAIN_SGD_MOMENTUM':
    0.9,
    'TRAIN_GPUS':
    4,
    'TRAIN_BATCH_SIZE':
    16,
    'TRAIN_TBLOG':
    False,
    'TRAIN_TBLOG_STEP':
    50,
    'TRAIN_LOG_STEP':
    20,
    'TRAIN_IMG_LOG':
    True,
    'TRAIN_TOP_K_PERCENT_PIXELS':
    0.15,
    'TRAIN_SEQ_TRAINING_FREEZE_PARAMS': ['patch_wise_id_bank'],
    'TRAIN_SEQ_TRAINING_START_RATIO':
    0.5,
    'TRAIN_HARD_MINING_RATIO':
    0.5,
    'TRAIN_EMA_RATIO':
    0.1,
    'TRAIN_CLIP_GRAD_NORM':
    5.0,
    'TRAIN_SAVE_STEP':
    5000,
    'TRAIN_MAX_KEEP_CKPT':
    8,
    'TRAIN_RESUME':
    False,
    'TRAIN_RESUME_CKPT':
    None,
    'TRAIN_RESUME_STEP':
    0,
    'TRAIN_AUTO_RESUME':
    True,
    'TRAIN_DATASET_FULL_RESOLUTION':
    False,
    'TRAIN_ENABLE_PREV_FRAME':
    False,
    'TRAIN_ENCODER_FREEZE_AT':
    2,
    'TRAIN_LSTT_EMB_DROPOUT':
    0.0,
    'TRAIN_LSTT_ID_DROPOUT':
    0.0,
    'TRAIN_LSTT_DROPPATH':
    0.1,
    'TRAIN_LSTT_DROPPATH_SCALING':
    False,
    'TRAIN_LSTT_DROPPATH_LST':
    False,
    'TRAIN_LSTT_LT_DROPOUT':
    0.0,
    'TRAIN_LSTT_ST_DROPOUT':
    0.0,
    'TEST_GPU_ID':
    0,
    'TEST_GPU_NUM':
    1,
    'TEST_FRAME_LOG':
    False,
    'TEST_DATASET':
    'youtubevos',
    'TEST_DATASET_FULL_RESOLUTION':
    False,
    'TEST_DATASET_SPLIT':
    'val',
    'TEST_CKPT_PATH':
    './pretrain_models/R50_AOTL_PRE_YTB_DAV.pth',
    'TEST_CKPT_STEP':
    None,
    'TEST_FLIP':
    False,
    'TEST_MULTISCALE': [1],
    'TEST_MAX_SHORT_EDGE':
    None,
    'TEST_MAX_LONG_EDGE':
    1040.0,
    'TEST_WORKERS':
    4,
    'DIST_ENABLE':
    True,
    'DIST_BACKEND':
    'nccl',
    'DIST_URL':
    'tcp://127.0.0.1:13241',
    'DIST_START_GPU':
    0,
    'DIR_DATA':
    '../VOS02/datasets',
    'DIR_DAVIS':
    '../VOS02/datasets/DAVIS',
    'DIR_YTB':
    '../VOS02/datasets/YTB',
    'DIR_STATIC':
    '../VOS02/datasets/Static',
    'DIR_ROOT':
    './',
    'DIR_RESULT':
    './result/default_R50_AOTL/PRE_YTB_DAV',
    'DIR_CKPT':
    './result/default_R50_AOTL/PRE_YTB_DAV/ckpt',
    'DIR_EMA_CKPT':
    './result/default_R50_AOTL/PRE_YTB_DAV/ema_ckpt',
    'DIR_LOG':
    './result/default_R50_AOTL/PRE_YTB_DAV/log',
    'DIR_TB_LOG':
    './result/default_R50_AOTL/PRE_YTB_DAV/log/tensorboard',
    'DIR_IMG_LOG':
    './img_logs',
    'DIR_EVALUATION':
    './results',
    'TEST_DATA_PATH':
    './datasets/Demo',
    'TEST_OUTPUT_PATH':
    './demo_output',
    'TEST_MIN_SIZE':
    None,
    'TEST_MAX_SIZE':
    1040.0
}
